# Generated by Django 5.2.4 on 2026-08-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('encounter_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('patient_nbr', models.BigIntegerField()),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('age_bracket', models.CharField(max_length=20)),
                ('time_in_hospital', models.IntegerField()),
                ('num_lab_procedures', models.IntegerField()),
                ('num_procedures', models.IntegerField()),
                ('num_medications', models.IntegerField()),
                ('number_outpatient', models.IntegerField()),
                ('number_emergency', models.IntegerField()),
                ('number_inpatient', models.IntegerField()),
                ('number_diagnoses', models.IntegerField()),
                ('max_glu_serum', models.CharField(blank=True, max_length=20, null=True)),
                ('a1c_result', models.CharField(blank=True, max_length=20, null=True)),
                ('change_med', models.CharField(max_length=10)),
                ('diabetes_med', models.CharField(max_length=10)),
                ('readmitted_raw', models.CharField(max_length=10)),
                ('readmitted_label', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('risk_score', models.FloatField()),
                ('predicted_label', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='audit.patient')),
            ],
            options={
                'unique_together': {('patient', 'model_version')},
            },
        ),
    ]
