# Generated by Django 6.1 on 2026-08-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_prediction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairnessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('protected_attribute', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShapExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_value', models.CharField(max_length=100)),
                ('shap_value', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shap_values', to='audit.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'model_version'], name='audit_shape_patient_fdd45f_idx')],
            },
        ),
    ]
