# Generated by Django 6.1 on 2026-09-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_modelmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationDisparity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=100)),
                ('protected_attribute', models.CharField(max_length=50)),
                ('subgroup', models.CharField(max_length=100)),
                ('subgroup_mean_shap', models.FloatField()),
                ('global_mean_shap', models.FloatField()),
                ('wasserstein_distance', models.FloatField()),
                ('n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_version', 'protected_attribute', 'feature_name'], name='audit_expla_model_v_313a89_idx')],
            },
        ),
    ]
