# Generated by Django 6.1 on 2026-09-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_explanationdisparity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationStability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('encounter_id', models.IntegerField()),
                ('perturbation', models.CharField(max_length=100)),
                ('original_score', models.FloatField()),
                ('perturbed_score', models.FloatField()),
                ('score_shift', models.FloatField()),
                ('classification_flipped', models.BooleanField()),
                ('original_top3', models.CharField(max_length=200)),
                ('perturbed_top3', models.CharField(max_length=200)),
                ('shared_top3_count', models.IntegerField()),
                ('jaccard_similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_version', 'shared_top3_count'], name='audit_expla_model_v_43860d_idx')],
            },
        ),
    ]
